## CSV Data to MySQL for use in VISDOM

This notebook can be used to construct an 'account' table and a 'meter_data' table in mysql, based on the csv files with data extracted from the prop39schools xml files, and an 'intervention' table based on the PEPS_Data.xlsx file available on the [prop39 data site](http://www.energy.ca.gov/efficiency/proposition39/data/).

The processed csv files can be downloaded as a zip file from [here](https://s3.amazonaws.com/BrianCoffey/PGE_csv_2.zip). They should be unzipped locally before running this script. Note that you may also need to `pip install xlrd` to be able to run pandas.read_excel for the intervention table data.

You must first create a database in mysql with your desired name (e.g. visdom_data_PGE), and create a data_db.cfg file to point to it, as described in the next section below.

The script will likely take about 40 minutes to complete on most modern laptops.

For your database to be ready for use in VISDOM, you will also need to load a local_weather table into your database. To do so you can follow the instructions in the [local-weather repo](https://github.com/sborgeson/local-weather) and use the prop39_config.csv file found [here](https://s3.amazonaws.com/BrianCoffey/prop39_weather_config.csv), which was prepared using the accompanying notebook. Or, if you want to get to the end point faster, you can download [this csv file](https://s3.amazonaws.com/BrianCoffey/prop39_weather_dump.csv), which was constructed using that repo, and then simply modify [this sql query](https://github.com/sborgeson/local-weather/blob/master/import_weather_data_mysql.sql) to point to that csv file and run it. Running the sql script will take about 20 minutes.

Once the database is set up, you can set it up as a DATA_SOURCE in VISDOM with the accompanying prop39_visdom_data_source.R file and test it via the sanitycheck function as follows:

```
source("prop39_visdom_data_source.R")
DATA_SOURCE = MyDataSource()
sanityCheckDataSource(DATA_SOURCE)
```

As described in more detail in the ID_mapping notebook in the same folder as this notebook, an account_uuid generally corresponds with an individual school and may have one or multiple meters associated with it, and may also have multiple interventions (or no interventions) associated with it.

### File locations, database config

Point this to the directory with the meter data csv files:

In [1]:
csv_dir = "PGE_csv"

Read your database connection details from a data_db.cfg file with the following format:

```
dbType=MySQL
user=[database user]
pass=[password (if applicable)]
db=[name of database]
```

In [2]:
db_pass = ""
with open('data_db.cfg','r') as f:
    for line in f:
        s = line.split("=")
        if s[0].strip() == "user":
            db_user = s[1].strip()
        if s[0].strip() == "pass":
            db_pass = ":" + s[1].strip()
        if s[0].strip() == "db":
            db_db = s[1].strip()

### Notebook config

In [3]:
import pandas as pd
import numpy as np
import mysql.connector, os, datetime
from sqlalchemy import create_engine

In [4]:
engine = create_engine('mysql+mysqlconnector://' + db_user + db_pass + '@localhost/' + db_db, echo=False)
conn = engine.connect()

### Reading the account table data from the _BILL.csv files

In [5]:
usecols = [
    'utility',
    'customer_name',
    'customer_city',
    'customer_zip',
    'customer_account',
    'lea_customer',
    'cds_code',
    'school_site_name',
    'school_city',
    'school_site_zip',
    'agreement',
    'rate_schedule_id'    
]

In [6]:
accounts_list = []
for root, dirs, files in os.walk(csv_dir):
    for f in files:
        if f.endswith('_BILL.csv'):
            df = pd.read_csv(os.path.join(root,f), usecols=usecols)
            df = df.drop_duplicates()
            accounts_list.extend(df.to_dict(orient='records'))

accounts_df = df.from_records(accounts_list)
accounts_df = accounts_df.drop_duplicates()
print len(accounts_df)
accounts_df.head(3)

4872


agreement       cds_code  customer_account customer_city  \
0  8496493494  1100170130419               NaN       HAYWARD   
1  8496493494  1100176106751               NaN       HAYWARD   
2  5637199749  1612340000000               NaN        NEWARK   

                        customer_name customer_zip  lea_customer  \
0  ALAMEDA COUNTY OFFICE OF EDUCATION   94544-1136           NaN   
1  ALAMEDA COUNTY OFFICE OF EDUCATION   94544-1136           NaN   
2      NEWARK UNIFIED SCHOOL DISTRICT   94560-2554           NaN   

  rate_schedule_id school_city                  school_site_name  \
0             E19S     Hayward          Alameda County Community   
1             E19S     Hayward  Alameda County Special Education   
2           HA10SX      Newark                               LEA   

  school_site_zip             utility  
0      94544-1136  PacificGasElectric  
1      94544-1136  PacificGasElectric  
2      94560-0385  PacificGasElectric

In [7]:
accounts_df.columns.tolist()

['agreement',
 'cds_code',
 'customer_account',
 'customer_city',
 'customer_name',
 'customer_zip',
 'lea_customer',
 'rate_schedule_id',
 'school_city',
 'school_site_name',
 'school_site_zip',
 'utility']

In [8]:
accounts_df.columns = [
 'meter_uuid',
 'account_uuid',
 'customer_account',
 'customer_city',
 'customer_name',
 'customer_zip',
 'lea_customer',
 'rate_schedule_id',
 'school_city',
 'school_site_name',
 'school_site_zip',
 'utility_name'
]

In [9]:
accounts_df['zip5'] = accounts_df['school_site_zip'].str[:5]
accounts_df.head(3)

meter_uuid   account_uuid  customer_account customer_city  \
0  8496493494  1100170130419               NaN       HAYWARD   
1  8496493494  1100176106751               NaN       HAYWARD   
2  5637199749  1612340000000               NaN        NEWARK   

                        customer_name customer_zip  lea_customer  \
0  ALAMEDA COUNTY OFFICE OF EDUCATION   94544-1136           NaN   
1  ALAMEDA COUNTY OFFICE OF EDUCATION   94544-1136           NaN   
2      NEWARK UNIFIED SCHOOL DISTRICT   94560-2554           NaN   

  rate_schedule_id school_city                  school_site_name  \
0             E19S     Hayward          Alameda County Community   
1             E19S     Hayward  Alameda County Special Education   
2           HA10SX      Newark                               LEA   

  school_site_zip        utility_name   zip5  
0      94544-1136  PacificGasElectric  94544  
1      94544-1136  PacificGasElectric  94544  
2      94560-0385  PacificGasElectric  94560

In [10]:
reals = accounts_df[['account_uuid']].applymap(np.isreal)
accounts_df = accounts_df[reals['account_uuid']]
len(accounts_df)

4864

In [11]:
accounts_df = accounts_df.drop_duplicates(subset=['meter_uuid'], keep='last')
len(accounts_df)

3177

In [12]:
accounts_df = accounts_df.dropna(subset=['zip5'])
len(accounts_df)

2575

### Creating the account table in the desired format and writing to it

In [13]:
create_table_sql = '''
CREATE TABLE `account` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_uuid` varchar(20) DEFAULT NULL,
  `meter_uuid` varchar(20) DEFAULT NULL,
  `zip5` varchar(5) DEFAULT NULL,
  `customer_account` varchar(50) DEFAULT NULL,
  `customer_city` varchar(50) DEFAULT NULL,
  `customer_name` varchar(50) DEFAULT NULL,
  `customer_zip` varchar(10) DEFAULT NULL,
  `lea_customer` varchar(50) DEFAULT NULL,
  `rate_schedule_id` varchar(50) DEFAULT NULL,
  `school_city` varchar(50) DEFAULT NULL,
  `school_site_name` varchar(100) DEFAULT NULL,
  `school_site_zip` varchar(10) DEFAULT NULL,
  `utility_name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `zip5_meter_uuid_idx` (`METER_UUID`,`zip5`),
  KEY `account_uuid_idx` (`ACCOUNT_UUID`),
  KEY `meter_uuid_idx` (`METER_UUID`)
)
'''

conn.execute('DROP TABLE IF EXISTS `account`;')
conn.execute(create_table_sql)

In [14]:
accounts_df.to_sql(name='account', con=engine, if_exists='append', index=False)

Quick test to make sure it's working:

In [15]:
pd.read_sql('SELECT * FROM account LIMIT 3;', con=engine)

id   account_uuid  meter_uuid   zip5 customer_account customer_city  \
0   1  1100176106751  8496493494  94544             None       HAYWARD   
1   2  1612340000000  5637199749  94560             None        NEWARK   
2   3  1612340130054  5637199200  94560             None        NEWARK   

                        customer_name customer_zip lea_customer  \
0  ALAMEDA COUNTY OFFICE OF EDUCATION   94544-1136         None   
1      NEWARK UNIFIED SCHOOL DISTRICT   94560-2554         None   
2      NEWARK UNIFIED SCHOOL DISTRICT   94560-2554         None   

  rate_schedule_id school_city                  school_site_name  \
0             E19S     Hayward  Alameda County Special Education   
1            HA10S      Newark                               LEA   
2             A10S      Newark              Newark Memorial High   

  school_site_zip        utility_name  
0      94544-1136  PacificGasElectric  
1      94560-0385  PacificGasElectric  
2      94560-5007  PacificGasElectric

In [16]:
pd.read_sql('SELECT COUNT(*) FROM account;', con=engine)

COUNT(*)
0      2575

In [17]:
pd.read_sql('SELECT COUNT(DISTINCT(meter_uuid)) FROM account;', con=engine)

COUNT(DISTINCT(meter_uuid))
0                         2575

### Creating the intervention table

The following will read the interventions data from the PEPS_data.xlsx file, add the appropriate account_uuid to each entry (if applicable, Null otherwise) by left-merging with the accounts_df table, then edits column names for a few columns to keep them under the requisite 64 characters, and then writes it to a mysql table. 

In [18]:
accounts_df['site_pair'] = accounts_df['school_city'] + "_" + accounts_df['school_site_name']

interventions_df = pd.read_excel('PEPS_Data.xlsx', sheetname='Data- Approved EEPs')

interventions_df['site_pair'] = interventions_df['Site City'] + "_" + interventions_df['Site Name']
interventions_df = pd.merge(interventions_df,accounts_df[['site_pair','account_uuid']],how='left',on='site_pair')
del interventions_df['site_pair']

replacement_column_names = [
    'Grant Amount Req Based on Single or Multiple Years Allocation',
    'Grant Amount Req',
    'Were Planning Funds Requested from CA Department of Education',
    'Budget for Screening and Energy Audits Over Program Life',
    'Budget for Prop 39 Program Assistance Over Program Life',
    'Est First Yr Annual Electricity Production of PV Measure',
    'Est Total Rebates Plus Oth Non-Repayable Funds for PV Measure',
    'Est First Year Elec Prod of PPA Measure Generation System',
    'Est PPA Measure Elec Gen as Percent of Baseline Elec Usage'
]

k = 0
for j,i in enumerate(interventions_df.columns):
    if len(i) > 64:
        interventions_df.columns.values[j] = replacement_column_names[k]
        k += 1

conn.execute('DROP TABLE IF EXISTS `intervention`;')
interventions_df.to_sql(name='intervention', con=engine, chunksize=100)
conn.execute('ALTER TABLE intervention MODIFY account_uuid VARCHAR(20);')

### Creating the meter_data table in the desired format

In [19]:
create_table_sql = '''
CREATE TABLE `meter_data` (
  `meter_uuid` varchar(20) NOT NULL,
  `account_uuid` varchar(20) NOT NULL,
  `date` DATE NOT NULL,
  `zip5` varchar(5) DEFAULT NULL,
'''

for i in range(1,97):
    create_table_sql += "`h" + str(i) + "` int(11) DEFAULT NULL,\n"

create_table_sql += '''    
  PRIMARY KEY (`meter_uuid`,`date`),
  KEY `meter_uuid_idx` (`meter_uuid`),
  KEY `account_uuid_idx` (`account_uuid`),
  KEY `zip_Date_idx` (`date`,`zip5`),
  KEY `zip_idx` (`zip5`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
'''

conn.execute('DROP TABLE IF EXISTS `meter_data`;')
conn.execute(create_table_sql)

### Fill the meter table with data from the csv files

In [20]:
usecols = ['agreement', 'start']
for i in range(1,97):
    usecols.append('d' + str(i))

In [21]:
colnames = ['meter_uuid', 'date']
for i in range(1,97):
    colnames.append('h' + str(i))

In [22]:
for root, dirs, files in os.walk(csv_dir):
    for f in files:
        if f.endswith('_INTERVAL.csv'):
            df = pd.read_csv(os.path.join(root,f), usecols=usecols)
            if len(df) > 0:
                df.columns = colnames
                df = df.drop_duplicates()
                for i in range(1,97):
                    df['h' + str(i)] = df['h' + str(i)] * 1000
                df = pd.merge(df,accounts_df[['meter_uuid','account_uuid','zip5']],on='meter_uuid')
                df['date'] = pd.to_datetime(df['date'], unit='s')
                try:
                    df.to_sql(name='meter_data', con=engine, if_exists='append', index=False)
                except:
                    print "failed sql insert. meter_uuid:" + str(df['meter_uuid'][0]) + ", filename: " + f.split("_Pacific")[0] + "..."

failed sql insert. meter_uuid:8496493494, filename: 01100176106751_20122013...
failed sql insert. meter_uuid:5637199274, filename: 01612340135426_20122013...
failed sql insert. meter_uuid:5741361055, filename: 04615230123687_20122013...
failed sql insert. meter_uuid:1626781530, filename: 06616220630038_20122013...
failed sql insert. meter_uuid:6449693283, filename: 10739651030402_20122013...
failed sql insert. meter_uuid:64274618, filename: 12755151232107_20122013...
failed sql insert. meter_uuid:5158002781, filename: 15101571530302_20122013...
failed sql insert. meter_uuid:5158002781, filename: 15101571530310_20122013...
failed sql insert. meter_uuid:5158002772, filename: 15101576069496_20122013...
failed sql insert. meter_uuid:7689247028, filename: 20652012030047_20122013...
failed sql insert. meter_uuid:7689247028, filename: 20652012032357_20122013...
failed sql insert. meter_uuid:9227619884, filename: 29663572930048_20122013...
failed sql insert. meter_uuid:8417601597, filename: 29

### Causes of sql insert errors

Spot checks of these insert errors suggest that they (or at least many of them) are caused by attempting to insert rows that replicate the table's primary key, which is a combination of meter_uuid and date. Looking at the csv files for some of these errors do show that they are replicated data in some pairs of csv files. Below is an example, which covers the first sql insert error noted above:

```
failed sql insert. meter_uuid:8496493494, filename: 01100176106751_20122013...
```

This is caused by these two files being identical (this can also be verified with a text diff tool):

```
PGE_csv/2012-2013/Electricity/01100176106751_20122013_PacificGasElectric_ELECTRIC_20151104.xml_INTERVAL.csv
PGE_csv/2012-2013/Electricity/01100170130419_20122013_PacificGasElectric_ELECTRIC_20151104.xml_INTERVAL.csv
```

Digging further to see if the original xml files are different suggests that the files are not exactly the same (a text diff tool says they are different, but since they treat the xml as all one line it is difficult to tell how they are different), but inspecting their data trees manually suggests that they may indeed contain the same data. 

In [52]:
root = "PGE_csv/2012-2013/Electricity"
f = "01100176106751_20122013_PacificGasElectric_ELECTRIC_20151104.xml_INTERVAL.csv"
df = pd.read_csv(os.path.join(root,f), usecols=usecols)
df.head()

agreement       start      d1      d2      d3      d4      d5      d6  \
0  8496493494  1341126000  29.940  29.244  28.584  28.464  28.332  27.744   
1  8496493494  1341212400  30.924  29.724  30.984  28.788  29.640  30.420   
2  8496493494  1341298800  21.504  21.756  23.112  22.032  21.576  21.600   
3  8496493494  1341385200   5.700  34.416  26.676  24.336  23.856  23.880   
4  8496493494  1341471600  21.036  20.676  21.420  22.488  20.976  21.276   

       d7      d8   ...       d87     d88     d89     d90     d91     d92  \
0  28.140  29.460   ...    32.856  32.508  30.324  30.360  31.236  32.556   
1  30.156  31.092   ...    31.812  31.968  29.052  29.040  30.120  29.712   
2  21.840  21.660   ...    25.776  24.672  23.520  24.732  24.204  19.752   
3  23.604  23.628   ...    24.732  24.240  22.596  22.704  22.356  22.740   
4  20.832  20.508   ...    30.072  35.196  25.692  24.360  25.008  30.636   

      d93     d94     d95     d96  
0  31.800  30.696  30.300  30.000  
1  30.444  29.136  23.712  22.128  
2   0.000   0.000   0.000   0.000  
3  22.512  23.544  22.068  21.780  
4  22.560  23.076  24.720  22.440  

[5 rows x 98 columns]

In [53]:
root = "PGE_csv/2012-2013/Electricity"
f = "01100170130419_20122013_PacificGasElectric_ELECTRIC_20151104.xml_INTERVAL.csv"
df = pd.read_csv(os.path.join(root,f), usecols=usecols)
df.head()

agreement       start      d1      d2      d3      d4      d5      d6  \
0  8496493494  1341126000  29.940  29.244  28.584  28.464  28.332  27.744   
1  8496493494  1341212400  30.924  29.724  30.984  28.788  29.640  30.420   
2  8496493494  1341298800  21.504  21.756  23.112  22.032  21.576  21.600   
3  8496493494  1341385200   5.700  34.416  26.676  24.336  23.856  23.880   
4  8496493494  1341471600  21.036  20.676  21.420  22.488  20.976  21.276   

       d7      d8   ...       d87     d88     d89     d90     d91     d92  \
0  28.140  29.460   ...    32.856  32.508  30.324  30.360  31.236  32.556   
1  30.156  31.092   ...    31.812  31.968  29.052  29.040  30.120  29.712   
2  21.840  21.660   ...    25.776  24.672  23.520  24.732  24.204  19.752   
3  23.604  23.628   ...    24.732  24.240  22.596  22.704  22.356  22.740   
4  20.832  20.508   ...    30.072  35.196  25.692  24.360  25.008  30.636   

      d93     d94     d95     d96  
0  31.800  30.696  30.300  30.000  
1  30.444  29.136  23.712  22.128  
2   0.000   0.000   0.000   0.000  
3  22.512  23.544  22.068  21.780  
4  22.560  23.076  24.720  22.440  

[5 rows x 98 columns]

To see how widespread this duplication in the underlying csv data is in causing the sql insert errors, consider comparisons of all of their top lines via pandas and identifying duplicates as shown below. This suggests that 353 of the 383 sql insert errors may indeed be caused by duplication in the csv data. The identified duplicates pertain to 165 different meter_uuids.

In [37]:
top_lines = []
file_names = []
for root, dirs, files in os.walk(csv_dir):
    for f in files:
        if f.endswith('_INTERVAL.csv'):
            df = pd.read_csv(os.path.join(root,f), usecols=usecols)
            if len(df) > 0:
                file_names.append(f)
                top_lines.append(df.to_dict(orient='records')[0])

In [41]:
top_lines_df = pd.DataFrame.from_records(top_lines)
top_lines_df.head()

agreement       d1     d10    d11     d12     d13      d14      d15  \
0  8.496493e+09  29.9400  28.992  27.24  28.776  28.344  29.1720  27.6600   
1  8.496493e+09  29.9400  28.992  27.24  28.776  28.344  29.1720  27.6600   
2  5.637200e+09   5.5600   5.160   5.08   5.000   5.200   5.0800   5.1200   
3  5.637200e+09   0.2400   0.240   0.24   0.360   0.240   0.2400   0.3600   
4  5.637199e+09   7.2336   7.320   7.32   7.128   7.128   7.0464   7.0464   

       d16      d17      ...          d89       d9    d90     d91     d92  \
0  28.8720  27.8640      ...       30.324  27.6600  30.36  31.236  32.556   
1  28.8720  27.8640      ...       30.324  27.6600  30.36  31.236  32.556   
2   5.0800   5.0800      ...        5.440   5.1600   5.48   5.400   5.400   
3   0.2400   0.2400      ...        0.360   0.3600   0.24   0.360   0.240   
4   6.9568   6.9568      ...        0.000   7.4144   0.00   0.000   0.000   

     d93     d94    d95    d96         start  
0  31.80  30.696  30.30  30.00  1.341126e+09  
1  31.80  30.696  30.30  30.00  1.341126e+09  
2   5.44   5.400   5.32   5.36  1.341126e+09  
3   0.36   0.240   0.24   0.36  1.341126e+09  
4   0.00   0.000   0.00   0.00  1.355990e+09  

[5 rows x 98 columns]

In [43]:
top_lines_df['filename'] = file_names
top_lines_df.head()

agreement       d1     d10    d11     d12     d13      d14      d15  \
0  8.496493e+09  29.9400  28.992  27.24  28.776  28.344  29.1720  27.6600   
1  8.496493e+09  29.9400  28.992  27.24  28.776  28.344  29.1720  27.6600   
2  5.637200e+09   5.5600   5.160   5.08   5.000   5.200   5.0800   5.1200   
3  5.637200e+09   0.2400   0.240   0.24   0.360   0.240   0.2400   0.3600   
4  5.637199e+09   7.2336   7.320   7.32   7.128   7.128   7.0464   7.0464   

       d16      d17                        ...                          \
0  28.8720  27.8640                        ...                           
1  28.8720  27.8640                        ...                           
2   5.0800   5.0800                        ...                           
3   0.2400   0.2400                        ...                           
4   6.9568   6.9568                        ...                           

        d9    d90     d91     d92    d93     d94    d95    d96         start  \
0  27.6600  30.36  31.236  32.556  31.80  30.696  30.30  30.00  1.341126e+09   
1  27.6600  30.36  31.236  32.556  31.80  30.696  30.30  30.00  1.341126e+09   
2   5.1600   5.48   5.400   5.400   5.44   5.400   5.32   5.36  1.341126e+09   
3   0.3600   0.24   0.360   0.240   0.36   0.240   0.24   0.36  1.341126e+09   
4   7.4144   0.00   0.000   0.000   0.00   0.000   0.00   0.00  1.355990e+09   

                                            filename  
0  01100170130419_20122013_PacificGasElectric_ELE...  
1  01100176106751_20122013_PacificGasElectric_ELE...  
2  01612340000000_20122013_PacificGasElectric_ELE...  
3  01612340116301_20122013_PacificGasElectric_ELE...  
4  01612340130054_20122013_PacificGasElectric_ELE...  

[5 rows x 99 columns]

In [44]:
duplicated_top_lines = top_lines_df[top_lines_df.duplicated(subset=usecols, keep=False)]
duplicated_top_lines.head()

agreement     d1     d10     d11     d12     d13     d14     d15  \
0   8.496493e+09  29.94  28.992  27.240  28.776  28.344  29.172  27.660   
1   8.496493e+09  29.94  28.992  27.240  28.776  28.344  29.172  27.660   
5   5.637199e+09   4.96   5.600   5.600   5.680   5.440   5.600   5.520   
6   5.637199e+09   4.96   5.600   5.600   5.680   5.440   5.600   5.520   
18  2.657846e+09   0.00   4.368   3.816   3.640   3.152   3.544   4.664   

       d16     d17                        ...                             d9  \
0   28.872  27.864                        ...                          27.66   
1   28.872  27.864                        ...                          27.66   
5    5.680   5.600                        ...                           5.52   
6    5.680   5.600                        ...                           5.52   
18   4.536   3.616                        ...                           4.08   

      d90     d91     d92    d93     d94    d95    d96         start  \
0   30.36  31.236  32.556  31.80  30.696  30.30  30.00  1.341126e+09   
1   30.36  31.236  32.556  31.80  30.696  30.30  30.00  1.341126e+09   
5    5.44   5.760   5.600   5.36   4.720   4.32   4.32  1.341126e+09   
6    5.44   5.760   5.600   5.36   4.720   4.32   4.32  1.341126e+09   
18    NaN     NaN     NaN    NaN     NaN    NaN    NaN  1.365664e+09   

                                             filename  
0   01100170130419_20122013_PacificGasElectric_ELE...  
1   01100176106751_20122013_PacificGasElectric_ELE...  
5   01612340130484_20122013_PacificGasElectric_ELE...  
6   01612340135426_20122013_PacificGasElectric_ELE...  
18  03739810000000_20122013_PacificGasElectric_ELE...  

[5 rows x 99 columns]

In [56]:
len(duplicated_top_lines), len(duplicated_top_lines[['agreement','start']].drop_duplicates()), len(duplicated_top_lines[['agreement']].drop_duplicates()), 

(645, 292, 165)

In [51]:
len(duplicated_top_lines) - len(duplicated_top_lines[['agreement','start']].drop_duplicates())

353

note that there are 383 failed inserts above, so this duplication of 353 top-rows could explain most of them

the first 5 fails are:

```
failed sql insert. meter_uuid:8496493494, filename: 01100176106751_20122013...
failed sql insert. meter_uuid:5637199274, filename: 01612340135426_20122013...
failed sql insert. meter_uuid:5741361055, filename: 04615230123687_20122013...
failed sql insert. meter_uuid:1626781530, filename: 06616220630038_20122013...
failed sql insert. meter_uuid:6449693283, filename: 10739651030402_20122013...
```

In [48]:
duplicated_top_lines[['agreement','filename']].head(10)

agreement                                           filename
0   8.496493e+09  01100170130419_20122013_PacificGasElectric_ELE...
1   8.496493e+09  01100176106751_20122013_PacificGasElectric_ELE...
5   5.637199e+09  01612340130484_20122013_PacificGasElectric_ELE...
6   5.637199e+09  01612340135426_20122013_PacificGasElectric_ELE...
18  2.657846e+09  03739810000000_20122013_PacificGasElectric_ELE...
26  2.657846e+09  03739816107395_20122013_PacificGasElectric_ELE...
27  5.741361e+09  04615230000000_20122013_PacificGasElectric_ELE...
29  5.741361e+09  04615230123687_20122013_PacificGasElectric_ELE...
32  2.084624e+09  06616220118729_20122013_PacificGasElectric_ELE...
33  2.084624e+09  06616220630038_20122013_PacificGasElectric_ELE...

### Quick tests to make sure it's done so properly

In [23]:
pd.read_sql('SELECT * FROM meter_data LIMIT 3;', con=engine)

meter_uuid    account_uuid        date   zip5    h1    h2    h3    h4  \
0  1021789005  44697326049563  2014-01-07  95060  2880     0  6160  2720   
1  1021789379  44697326049563  2014-01-08  95060   880   880   960   880   
2  1021789379  44697326049563  2014-01-09  95060  1040  1440  1120  1200   

     h5    h6   ...       h87     h88     h89     h90     h91     h92     h93  \
0  2240  2480   ...       NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1   800   880   ...    1600.0  1680.0  1600.0  1760.0  1600.0  1600.0  1360.0   
2  1120  1120   ...     960.0   720.0   880.0   880.0   880.0   880.0   800.0   

      h94     h95     h96  
0     NaN     NaN     NaN  
1  1120.0  1120.0  1280.0  
2   960.0   880.0   880.0  

[3 rows x 100 columns]

In [24]:
pd.read_sql('SELECT COUNT(*) FROM meter_data;', con=engine)

COUNT(*)
0   1286757

### Coordinating between tables to make sure they match

In [25]:
conn.execute('DELETE FROM account WHERE meter_uuid NOT IN (SELECT DISTINCT(meter_uuid) FROM meter_data);')

In [26]:
pd.read_sql('SELECT COUNT(*) FROM account;', con=engine)

COUNT(*)
0      2186

### Minor cludge that could be done better

This meter_uuid had only one meter_data day record associated with it for some reason, which would cause errors if allowed to stay in the database.

In [27]:
conn.execute("DELETE FROM account WHERE meter_uuid = '1021789005';")
conn.execute("DELETE FROM meter_data WHERE meter_uuid = '1021789005';")